### ISSUE TITLE
direct.fen.json outdated for FEN v1.18.21

### ISSUE THREAD

**Issue by baltzis** [a4k-openproject/json.openplayers#47]
direct.fen.json does no longer work for TV shows with the latest version of FEN (1.18.21). As a result, the following error is produced (see also the attached file). Unfortunately, I do not know how to update this.

2020-12-06 11:07:02.570 T:5848   ERROR: EXCEPTION Thrown (PythonToCppException) :
-->Python callback/script returned the following error<--
  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
  Error Type: <type 'exceptions.AttributeError'>
  Error Contents: Sources instance has no attribute 'season'
  Traceback (most recent call last):
  File "C:\Kodi\portable_data\addons\plugin.video.fen\resources\lib\fen.py", line 5, in <module>
    routing(argv[2])
  File "C:\Kodi\portable_data\addons\plugin.video.fen\resources\lib\modules\router.py", line 114, in routing
  Sources().playback_prep(params)
  File "C:\Kodi\portable_data\addons\plugin.video.fen\resources\lib\modules\sources.py", line 69, in playback_prep
      else: self._grab_meta()
  File "C:\Kodi\portable_data\addons\plugin.video.fen\resources\lib\modules\sources.py", line 514, in _grab_meta
      episodes_data = tikimeta.season_episodes_meta(self.meta['tmdb_id'], self.meta['tvdb_id'], self.season, 
      self.meta['tvdb_summary']['airedSeasons'], self.meta['season_data'], meta_user_info)
  AttributeError: Sources instance has no attribute 'season'
-->End of Python script error report<--
2020-12-06 11:07:25.715 T:12952  NOTICE: Stopping player

[kodi.log](https://github.com/a4k-openproject/json.openplayers/files/5648521/kodi.log)

**Comment by xyzfre** [comment]
I did notice yesterday as well same issue Doesn’t work with TV shows I get the same exact error as posted above

**Comment by drinfernoo** [comment]
Maybe @tikipeter would have a look?

**Comment by Tikipeter** [comment]
@drinfernoo 
This has just been fixed (issue with Fen, not the player).
